### ISSUE TITLE
Mandatory file extensions for ESM file resolution

### ISSUE THREAD

**Issue by tex0l** [altano/npm-packages#99]
Hi!

I'm currently using your package `@altano/satori-fit-text` in a project which uses [Astro](astro.build) with node 20, and after upgrading dependencies, it now fails with the following error:

`[ERROR] Cannot find module '/path/to/project/node_modules/@altano/satori-fit-text/dist/fitText' imported from /path/to/project/tex0l.github.io-astro/node_modules/@altano/satori-fit-text/dist/index.js`

It seems it is because since your repo overhaul, you no longer bundle the whole code in one file (you had dynamic imports in that bundle which contained the `.js`), and leave the imports as you wrote them: without the file extensions in the imports (see https://github.com/altano/npm-packages/blob/66cc7d79122cfc2b482b3fa7fa3c937fdf6626ef/packages/satori-fit-text/src/index.ts#L1 for example), which are mandatory for the ESM file resolution: https://nodejs.org/api/esm.html#mandatory-file-extensions.

Would it be possible to add the file extensions to your imports please?

Thanks for the package anyway :). If you don't have time to do it, I'll probably rewrite what you did in my own code directly.

**Comment by altano** [comment]
Oh yeah sounds like I screwed that up. If you can help me reproduce the issue easily I’ll fix it. Do you have a stackblitz or repo?

**Comment by altano** [comment]
(And if you don’t have one handy I’ll still fix it, I understand the issue)

**Comment by tex0l** [comment]
Here it is: https://stackblitz.com/edit/vitejs-vite-rckfei?file=tsconfig.app.json

The only modification made to the boilerplate's configuration is that I switched the moduleResolution in the tsconfig.json to `nodenext`

**Comment by tex0l** [comment]
Here it is : https://stackblitz.com/edit/vitejs-vite-rckfei?file=tsconfig.app.json

If your run `npm run build` you'll get a similar error. I mostly fiddled with the TS config. to make sure the `nodenext` resolution was used compared to the raw boilerplate.

**Comment by altano** [comment]
Great, ty, will get this fixed next week!

**Comment by altano** [comment]
This is fixed in @altano/satori-fit-text@0.1.4
